[clipboard.copyFullPageScreenshot]
description = "Copies a full page screenshot"
match = """
  copy (the |) full (page |) (screenshot |) (of |) (the | this |) (tab | page | article | site) (to clipboard |)
  copy (the |) (tab's |) full (page |) (screenshot |) (to clipboard |)
  copy (full | page) screenshot (to clipboard |)
  screenshot full (page |) to clipboard
"""

[[clipboard.copyFullPageScreenshot.example]]
phrase = "Copy full page screenshot"

[[clipboard.copyFullPageScreenshot.example]]
phrase = "Copy page screenshot"
test = true

[[clipboard.copyFullPageScreenshot.example]]
phrase = "copy a whole page screenshot"
test = true

[clipboard.copyLink]
description = "Copies the link of the current tab"
match = """
  copy (the |) (this |) (tab's |) (link{s} | url) (of this tab |) (to clipboard |)
"""

[[clipboard.copyLink.example]]
phrase = "Copy link"

[[clipboard.copyLink.example]]
phrase = "Copy links"
test = "true"

[clipboard.copyMarkdownLink]
description = "Copies the Markdown [title](link)"
match = """
  copy (the |) markdown link of (the | this |) tab (to clipboard |)
  copy (the |) markdown (tab |) link (to clipboard |)
  copy (the |) markdown title and link (to clipboard |)
  copy (the |) markdown link and title (to clipboard |)
"""

[[clipboard.copyMarkdownLink.example]]
phrase = "Copy Markdown link"

[clipboard.copyRichLink]
description = "Copies the HTML title and link"
match = """
  copy (the |) (rich | html) link of (the | this |) tab (to clipboard |)
  copy (the |) (rich | html) (tab |) link (to clipboard |)
  copy (the |) (rich | html) link (to clipboard |)
  copy (the |) title and link (to clipboard |)
  copy (the |) link and title (to clipboard |)
"""

[[clipboard.copyRichLink.example]]
phrase = "Copy HTML link"

[clipboard.copyScreenshot]
description = "Copies the screenshot of the visible page"
match = """
  copy (the |) screenshot of (the | this |) (tab | page | article) (to clipboard |)
  copy (the |) (tab's |) screenshot (to clipboard |)
  screenshot (this |) (tab |) to clipboard
  screenshot (page |)
"""

[[clipboard.copyScreenshot.example]]
phrase = "Copy screenshot"

[[clipboard.copyScreenshot.example]]
phrase = "Screenshot"
test = true

[[clipboard.copyScreenshot.example]]
phrase = "Take a screenshot"
test = true

[[clipboard.copyScreenshot.example]]
phrase = "Take a screenshot of the page"
test = true

[[clipboard.copyScreenshot.example]]
phrase = "copy a screenshot of the page"
test = true

[[clipboard.copyScreenshot.example]]
phrase = "screenshot this page"
test = true

[clipboard.copySelection]
description = "Copies the selection"
match = """
  copy (this |) (selection |) (to clipboard |)
"""

[[clipboard.copySelection.example]]
phrase = "Copy selection"

[clipboard.copyTitle]
description = "Copies the title of the current tab"
match = """
  copy (the |) title of (the | this |) tab (to clipboard |)
  copy (the |) tab title (to clipboard |)
  copy title (to clipboard |)
"""

[[clipboard.copyTitle.example]]
phrase = "Copy tab title"

[clipboard.copyImage]
description = "Copies the best image in the current tab" 
match = """ 
  copy (the | this |) image (to clipboard |)
""" 

[[clipboard.copyImage.example]] 
phrase = "Copy image"

[clipboard.paste]
description = "Pastes from the clipboard"
match = """
  paste (the |) (selection | clipboard |)
"""

[[clipboard.paste.example]]
phrase = "Paste"
