[timer.set]
description = "Set timer"
match = """
    (set | open | show | start | create | make |) (a |) (timer | countdown) (for |) [time]
"""

[[timer.set.example]]
phrase = "Set timer for 2 hours and 5 minutes"


[timer.close]
description = "Close timer"
match = """
    (close | exit | stop | cancel | end) (this | the | current |) (timer | countdown)
"""

[[timer.close.example]]
phrase = "close timer"



[timer.reset]
description = "Reset timer"
match = """
    (reset | restart) (this | the | current |) (timer | countdown)
"""

[[timer.reset.example]]
phrase = "reset timer"



[timer.pause]
description = "Pause timer"
match = """
    pause (this | the | current |) (timer | countdown)
"""

[[timer.pause.example]]
phrase = "pause timer"

[timer.unpause]
description = "Unpause timer"
match = """
    (unpause | resume | start) (this | the | current |) (timer | countdown)
"""

[[timer.unpause.example]]
phrase = "unpause timer"

