[window.switch]
description = "Switch the current window"
match = """
  (switch | activate | focus) (the | to |) next window [direction=next]
  (switch | activate | focus) (the | to |) (previous | last) window [direction=back]
"""

[window.downloads]
description = "Open the downloads"
match = """
  (show | open |) downloads (menu |)
"""
[[window.downloads.example]]
phrase = "open downloads"

[window.quitApplication]
description = "Close Firefox"
match = """
  (close | quit | exit | shutdown) firefox
"""

[[window.quitApplication.example]]
phrase = "Close Firefox"

[window.combine]
description = "Combine all windows"
match = """
  combine all windows (into |) (one |) (window |)
  combine tabs (into |) (one |) window
"""

[[window.combine.example]]
phrase = "combine all windows"

[[window.combine.example]]
phrase = "combine all windows into one"
test = true

[[window.combine.example]]
phrase = "combine tabs into one window"
test = true

[window.close]
description = "Closes the window"
match = """
  close (the |) (this |) (all |) (window{s}) (for me |)
"""

[[window.close.example]]
phrase = "Close window"

[[window.close.example]]
phrase = "Close this window"
test = true

[[window.close.example]]
phrase = "Close all windows"
test = true
