[self.cancelIntent]
description = "Cancels input, immediately closing the popup"
match = """
  cancel
  nevermind
  never mind
"""

[[self.cancelIntent.example]]
phrase = "nevermind"
test = true

[self.openIntentViewer]
description = "Opens the intent viewer (probably this page)"
match = """
  (show | open) all intents (for me |)
  (show | open) intent viewer (for me|)
"""

[self.openLexicon]
description = "Opens the lexicon: a hand-written help file that indicates things you can say"
match = """
  tell me about (this | firefox voice | this extension | voice)
  help
  what (else |) (can | should) (I | you) (do | say | ask) (you | from you | of you |)
  (hello | hi)
  what commands (can | could | will | would |) (I | you |) (say | follow | use | speak |)
  (hello | hi |) how are you (doing |)
"""

[[self.openLexicon.example]]
phrase = "Tell me about Firefox Voice"

[[self.openLexicon.example]]
phrase = "Help"

[[self.openLexicon.example]]
phrase = "tell me about this"
test = true

[[self.openLexicon.example]]
phrase = "what can I do"
test = true

[[self.openLexicon.example]]
phrase = "what else can I say"
test = true

[[self.openLexicon.example]]
phrase = "what commands can you follow"
test = true

[[self.openLexicon.example]]
phrase = "hello how are you"
test = true

[[self.openLexicon.example]]
phrase = "What can I do?"

[[self.openLexicon.example]]
phrase = "what should I do"
test = true

[self.openOptions]
description = "Opens the options page"
match = """
  (open | open the | voice | firefox voice) (settings | options | preferences) (for me |)
  settings
  options
  preferences
"""

[[self.openOptions.example]]
phrase = "open settings for me"
test = true

[[self.openOptions.example]]
phrase = "voice settings"
test = true

[[self.openOptions.example]]
phrase = "firefox voice options"
test = true

[self.tellJoke]
description = "Someone asks for a joke or something funny"
match = """
  tell (me |) a joke
  say something funny
  make me laugh
"""

[[self.tellJoke.example]]
phrase = "Tell me a joke"

[[self.tellJoke.example]]
phrase = "Say something funny"

[[self.tellJoke.example]]
phrase = "Make me laugh"
